version: '3'

services:
  memcached:
    image: memcached:alpine

  mysql:
    image: mariadb
    ports:
      - "13306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password

  server:
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./public_html/:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password

  mailcatcher:
     image: schickling/mailcatcher
     ports:
       - "1025:1025"
       - "1080:1080"
     environment:
       MAILCATCHER_PORT: 1025
