version: '3'

services:
  memcached:
    image: memcached:latest

  mysql:
    image: mariadb
    ports:
      - "13306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password

  server:
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./public_html/:/var/www/html
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql_database
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
